"""add news searches table

Revision ID: 571f3cd25978
Revises: 3ea15b417fca
Create Date: 2026-07-08 13:37:52.073444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571f3cd25978'
down_revision: Union[str, Sequence[str], None] = '3ea15b417fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_searches_id'), 'news_searches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_searches_id'), table_name='news_searches')
    op.drop_table('news_searches')
    # ### end Alembic commands ###
