"""add unique constraint to news search symbol

Revision ID: 83d59ea767b6
Revises: 571f3cd25978
Create Date: 2026-07-08 22:59:33.026751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d59ea767b6'
down_revision: Union[str, Sequence[str], None] = '571f3cd25978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_searches_symbol'), 'news_searches', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_searches_symbol'), table_name='news_searches')
    # ### end Alembic commands ###
